### PR TITLE
Integrate sources from endlessm at V5.5.2

### PR DESCRIPTION
**Pull request by tomaspinho**

### CODE REVIEW

**Comment by imakiro** [comment]
`sudo ./dkms-install.sh`
is installing properly and working on both kernels 4.18 and 5.0.0 (tested on KDE Neon)

**Comment by hashlib** [comment]
Works fine on 5.0.0

**Comment by tomaspinho** [comment]
Giving it a few more days before I merge into master. Would like someone to test on 5.1.0 and 5.2.0 if possible.

**Comment by hashlib** [comment]
It doesn't work on 5.3

**Comment by tomaspinho** [comment]
@hashlib that one is being tracked as a separate issue. As 5.3 is still in RC, I will merge this later and then attempt a fix for 5.3

**Comment by acowley** [comment]
It's working for me on NixOS with kernel 5.1.19. I'll also mention that I've not been able to use Suspend on this desktop before because the rtl8821ce would not wake up properly the vast majority of the time, but I just tried a suspend/wake cycle and it came back fine. Only one test, but hopefully indicative of a real improvement.

**Comment by tomaspinho** [comment]
@acowley great news! Looks like we'll be able to close a couple of issues when this one is finally merged 🎉

**Comment by 9Lukas5** [comment]
It works fine on Ubuntu 19.04 with 5.2.6 kernel for me :+1: 
L

**Comment by tomaspinho** [comment]
Ok, taking the plunge and merging this one :crossed_fingers:

**Comment by gregory112** [comment]
Just want to verify this that it works in Arch Linux kernel 5.2.4, thank you. Laptop is Asus ROG Zephyrus GA502DU, both for 2.4 GHz and 5 GHz, with ASPM enabled.

**Comment by paulovieira** [comment]
Work well in Kubuntu 18.04.3 (kernel 5.0.0-37). I can suspend to ram and resume without any problems. Thanks.

**Comment by lenadi-moucina** [comment]
On Mageia7, rtl8822ce work correctly with kernel 5.1, but not with the newer. 
With kernel 5.3 or 5.4, I just can see the ssid of my neighbouring, not mine on Freebox.

**Pull request merged**
