### PR TITLE
Add License based on original files

### LINKED ISSUE #172: Please add License File
Olá Tomás 

I need a COPYRIGHT file in your repo to comply Fedora RPM packaging .

Thank you

### PR DESCRIPTION
**Pull request by tomaspinho**
Closes #172

### CODE REVIEW

**Comment by sergiomb2** [comment]
Thank you, approved !

**Comment by sergiomb2** [comment]
please move License.md to License

**Comment by tomaspinho** [comment]
File renamed

**Comment by sergiomb2** [comment]
For examples https://github.com/rpmfusion-infra/rfpkg or https://github.com/twaugh/patchutils 

on up right page we can read "About" -> "GPL-2.0 License",  that is the most important .

BTW I checked and https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project says that when can use COPYING or LICENSE ... 

Approved 

Thank you

**Pull request merged**
