### PR TITLE
Update rtl8821ce_halmac.c

### PR DESCRIPTION
**Pull request by SatanicRaw**
Add 32bit support.

### CODE REVIEW

**Comment by tomaspinho** [comment]
cool, but why? :upside_down_face:

**Comment by SatanicRaw** [comment]
Mmm, for old notebook's :) This module was added to the Calculate Linux distribution, plus they wrote this patch.

**Comment by tomaspinho** [comment]
This is a pretty new chip, surprised it managed to find itself on 32bit machines! Out of interest, would you be kind to link info on the hardware here?

**Comment by SatanicRaw** [comment]
No, I mean 32 bit OS :)

**Pull request merged**
